CREATE TABLE todo (
  id INT GENERATED ALWAYS AS IDENTITY NOT NULL  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  description VARCHAR(250) NOT NULL,
  date TIMESTAMP NOT NULL,
  completed Boolean DEFAULT false
);

